<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\Files\AppIcon.ico</ApplicationIcon>
    <AssemblyName>StormLauncher</AssemblyName>
    <RootNamespace>StormLauncher</RootNamespace>
    <Version>2.1.7</Version>
    <AssemblyVersion>2.1.7.0</AssemblyVersion>
    <FileVersion>2.1.7.0</FileVersion>
    <AssemblyTitle>STORM Fast Zero-UAC Launcher 2.1.7</AssemblyTitle>
    <Product>STORM Fast Zero-UAC Launcher 2.1.7</Product>
    <Title>STORM Fast Zero-UAC Launcher 2.1.7</Title>
    <Description>STORM Fast Zero-UAC Launcher 2.1.7</Description>
    <Company>STORM SOFT</Company>
    <Authors>ReiKatari</Authors>
    <Copyright>Copyright © 2026 STORM TEAM</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\Files\AppIcon.ico" Link="AppIcon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>