<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\Files\AppIcon.ico</ApplicationIcon>
    <Version>1.0.8</Version>
    <AssemblyVersion>1.0.8.0</AssemblyVersion>
    <FileVersion>1.0.8.0</FileVersion>
    <AssemblyTitle>STORM SYSTEM OPTIMIZER 1.0.8</AssemblyTitle>
    <Product>STORM SYSTEM OPTIMIZER 1.0.8</Product>
    <Title>STORM SYSTEM OPTIMIZER 1.0.8</Title>
    <Description>STORM SYSTEM OPTIMIZER 1.0.8</Description>
    <Company>STORM TEAM</Company>
    <Authors>STORM TEAM</Authors>
    <Copyright>Copyright © 2026 STORM TEAM</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\StormSystemOptimizer\bin\Release\net8.0-windows\win-x64\publish\StormSystemOptimizer.exe" Link="Payload\StormSystemOptimizer.exe" />
    <EmbeddedResource Include="..\..\Files\STORM_Certificate.cer" Link="Payload\STORM_Certificate.cer" />
    <EmbeddedResource Include="..\..\Files\AppIcon.ico" Link="Payload\AppIcon.ico" />
  </ItemGroup>

</Project>
